#!/usr/bin/env python3

from venvstarter import ignite
import os

this_dir = os.path.dirname(__file__)

with open(os.path.join(this_dir, "requirements.txt"), "r") as fle:
    deps = [line.strip() for line in fle.readlines() if line.strip()]

ignite(this_dir, "sphinx-build", deps=deps, min_python_version=3.6)
